name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-package-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: kianalikhani/www:latest
          push: true

      - name: Rancher Deploy
        uses: yantadeu/rancher-deploy-action@v0.0.3
        env:
          RANCHER_ACCESS_KEY: ${{ secrets.RANCHER_USERNAME }}
          RANCHER_SECRET_KEY: ${{ secrets.RANCHER_PASSWORD }}
          RANCHER_URL_API: 'https://rancher.alikhani.io/v3'
          SERVICE_NAME: 'kianalikhani-www'
          DOCKER_IMAGE: 'kianalikhani/www:latest'
          DOCKER_IMAGE_LATEST: 'kianalikhani/www:latest'
